
redis: { label: "Redis (Cache/Queue)" }
tor: { label: "Tor (Privacy Network)" }
web: { label: "Web Frontend" }
dashboard: { label: "Dashboard" }
discovery: { label: "Discovery Service" }
checker_btc: { label: BTC Checker}
checker_btc.shape: circle
checker_zec: { label: "ZEC Checker" }
checker_zec.shape: circle
btc_backend: { label: "BTC Backend" }

// Set ranks
{ rank = same; checker_btc; checker_zec; }
{ rank = same; redis; tor; }
{ rank = same; btc_backend; }

checker_zec -> web { label: "Fetches ZEC check jobs" }
checker_zec -> redis { label: "Stores ZEC check results" }

checker_btc -> btc_backend { label: "Fetches BTC worker data" }
checker_btc -> redis { label: "Stores BTC check results" }
checker_btc -> web { label: "Fetches BTC check jobs" }
checker_btc -> tor { label: "Connects to Tor servers" }


checker_btc -> btc_backend
btc_backend -> checker_btc
web -> redis { label: "Reads stale check requests" }
